### ISSUE TITLE
Installation step missing for Wheezy

### ISSUE THREAD

**Issue by DaddyTheRunner** [RPi-Distro/python-sense-hat#17]
The installation instructions need to include the following command to ensure the JPEG development package is installed before trying to install pillow under Wheezy:

`sudo apt-get install libjpeg-dev`

**Comment by thomas-kriechbaum** [comment]
+1 
took me some time to figure that out

**Comment by SteveAmor** [comment]
Fixed in PR #19

**Comment by XECDesign** [comment]
Wheezy is not officially supported.
