### ISSUE TITLE
Regarding the RTIMU used 

### ISSUE THREAD

**Issue by lpashwin** [RPi-Distro/python-sense-hat#23]
Is the RTIMU used in *sense_hat.py* the same as the one found here https://github.com/RPi-Distro/RTIMULib? I have observed that the comment in *sense_hat.py* states that the RTIMU used is a modified one. If so, would someone be kind enough to share the source code for the modified RTIMULib?

**Comment by bennuttall** [comment]
Yes it's the one in RPi-Distro.

**Comment by lpashwin** [comment]
Thanks for the info Ben!

**Comment by bennuttall** [comment]
No worries!
