### ISSUE TITLE
No module named RTIMU 

### ISSUE THREAD

**Issue by ichy-wayland** [RPi-Distro/python-sense-hat#32]
Hello, im starting with the sense-hat, but my programs always give this error: "ImportError: no module named RTIMU". Any suggestions on how to fix?
I installed the SenseHat module via pip.

**Comment by XECDesign** [comment]
Are you running Raspbian? If so, install sense-hat.

**Comment by ichy-wayland** [comment]
XECDesign, im running ArchLinux ARM

**Comment by XECDesign** [comment]
You will need to install this https://github.com/RPi-Distro/RTIMULib

It looks like there's a related package in AUR, but I can't guarantee that will work https://aur.archlinux.org/packages/python-sense-hat/

**Comment by ichy-wayland** [comment]
Worked, used the python-rtimulib, thanks!
