### ISSUE TITLE
OSError: Cannot detect RPi-Sense FB device

### ISSUE THREAD

**Issue by landchr** [RPi-Distro/python-sense-hat#41]
Getting this error message when I try to run sense hat I have ensured the device tree and I2C are enabled.  I have also added the two lines to /boot/config.txt of dtdebug=1 not sure what else to do

**Comment by XECDesign** [comment]
Could you take a look at this issue and provide all the information requested there https://github.com/RPi-Distro/python-sense-hat/issues/38 ?

**Comment by XECDesign** [comment]
Inactive
