### ISSUE TITLE
No suod apt-get install sense-hat

### ISSUE THREAD

**Issue by cristolmeth** [RPi-Distro/python-sense-hat#45]
Hi I am new to RPI's and Ubuntu in general. I have an Ubuntu image on my RPI and im trying to apt-get install the proper packages for the Sense hat. Whenever I run sudo apt-get install sense-hat -y I get a Unable to locate package sense-hat error. I think its because Ubunutu doesn't come with that package and it won't install it. Are there any work arounds?

**Comment by XECDesign** [comment]
Unfortunately, we don't maintain Ubuntu, so this isn't the place to report this issue.

**Comment by cristolmeth** [comment]
Do you know where the place to report this is I'm a little lost
On May 7, 2016 1:18 PM, "XECDesign" <notifications@github.com> wrote:
>
> Unfortunately, we don't maintain Ubuntu, so this isn't the place to
report this issue.

**Comment by XECDesign** [comment]
I am not sure, but I think I would start here. https://launchpad.net/ubuntu-mate

**Comment by bennuttall** [comment]
Ping @flexiondotorg
