### ISSUE TITLE
Sense Hat Diagram - locating I2C bus on test pads

### ISSUE THREAD

**Issue by mchobby** [RPi-Distro/python-sense-hat#5]
I'm looking for the diagram of the sense hat, I would like to identify the test pads (under the board) associated with the I2C bus (if any).

I would like to add an I2C clock on it... 
Someone could help in identifying the pads... or to locate the board diagram?

thanks

**Comment by XECDesign** [comment]
The full schematic is available here here:
https://www.raspberrypi.org/wp-content/uploads/2015/08/Sense-HAT-V1_0.pdf
https://github.com/raspberrypi/documentation/tree/master/hardware/sense-hat
