### ISSUE TITLE
OSError: Cannot detect Rpi-Sense FB device 

### ISSUE THREAD

**Issue by brunisgirl** [RPi-Distro/python-sense-hat#59]
I am using raspberry pi 3 and sense hat and get the above error.
I have tried everything in this link: 
https://github.com/RPi-Distro/python-sense-hat/issues/38

I still get the error. The LEDs go on when I connect the sense hat and off afterwards.
From demsg I get:
rpi-sense: 1-0046: Read from reg 240 failed
rpi-sense: probe of 1-0046 failed with error -22

Does this mean my sense hat is "fried"? (I forgot to add the legs before mounting the sense hat)

I appreciate any help.

Sahar

**Comment by copilco** [comment]
Exactly the same situation. 
RTIMULib works well 
The sensehat works well in rpi 2.

**Comment by brunisgirl** [comment]
I had to buy a new sensehat and now it works, I am afraid you might have fired it up as well.

**Comment by mmodlin** [comment]
I have done everything that every other issue has resolved.  Including re-flashing the SD card with the latest version of Jessie and updating the firmware.  I am using the Raspberry pi 3. RTiMULib returns values.  I get the same results from dmesg.  When running a sample file I receive the same error message.  I hope someone can help!

**Comment by buchbend** [comment]
Same here.

**Comment by XECDesign** [comment]
If you are seeing the issue and have tried to fix it, please report what you have tried, starting with a clean raspbian install. If it doesn't "just work" and it has never been plugged in the wrong way or otherwise short circuited , I would recommend returning it.

**Comment by mushu999** [comment]
Did you try this? Add
dtoverlay=rpi-sense
in /boot/config.txt to force sense HAT detection.
Might be required if you have anything else plugged in...see:
[ https://www.raspberrypi.org/forums/viewtopic.php?f=104&t=133244 ]
