### ISSUE TITLE
Another problematic pisense

### ISSUE THREAD

**Issue by ways** [RPi-Distro/python-sense-hat#66]
What an incredible cute, but picky device.

I tried for a long time to get it working with a Pi 3, without luck.

On a Pi2 (rev1.2) it works sometimes. That is, I've had it working for a few seconds with one of the examples, but then it freezes, and dmesg shows read errors. It's frozen until I pull power.

Most times I boot up, the rainbow color stays, and dmesg shows:

> pi@pisense:~ $ dmesg |grep -i sense
> [    7.451905] rpi-sense 1-0046: Read from reg 240 failed
> [    7.451983] rpi-sense: probe of 1-0046 failed with error -22

I've tried to reflash eeprom, but can never get past "2. Disable write protection:". I just get an IO error. So I can read out the eeprom, but not write new.

**Comment by XECDesign** [comment]
They definitely shouldn't be picky. A working sense hat 'just works' and if it has arrived in a state there it only work intermittently, I would recommend returning it.

**Comment by ways** [comment]
Ok, thanks. Will return.
