### ISSUE TITLE
Strange behavior set_pixel

### ISSUE THREAD

**Issue by paulocanedo** [RPi-Distro/python-sense-hat#73]
Hi,

```python
sense.clear()
sense.set_pixel(0, 0, 255, 0, 0)
```

When I use above code, all the LEDs in column 0 turns red, instead of just one LED, how can I find where the bug is? python lib, SenseHat firmware, board connection?

**Comment by XECDesign** [comment]
Could you run `sudo dd if=/dev/fb1 of=test.rgb565` and then upload test.rgb565?

**Comment by paulocanedo** [comment]
here is @XECDesign 
[test.zip](https://github.com/RPi-Distro/python-sense-hat/files/996137/test.zip)

**Comment by XECDesign** [comment]
So it's not the python lib. Given that I can't reproduce the problem, it's hard to investigate the rest. Are you overclocking or changing any of the timings at all?

**Comment by paulocanedo** [comment]
No over clock or any kind of hack... i have a raspbian fresh install and modified /boot/confia adding dtoverlay = sensehat . Thanks for your help, at least I know the problem isn't python lib.

**Comment by XECDesign** [comment]
Do you have another pi or another sense hat you could try? Do you have a logic analyser or a scope?
