### ISSUE TITLE
Getting error message

### ISSUE THREAD

**Issue by Forsinogul** [RPi-Distro/python-sense-hat#8]
I am getting the following error message: OSError: Cannot detect RPi-Sense FB device.  However all LED lights are on.

**Comment by XECDesign** [comment]
Hello, could you please provide the output of the following:
```
sudo apt-get install device-tree-compiler
uname -a
vcgencmd version
sudo dtc -I fs /proc/device-tree
```

**Comment by Forsinogul** [comment]
thank you for your help.  below is the output requested:
uname -a
Linux pi 4.1.6-v7+ #810 SMP PREEMPT Tue Aug 18 15:32:12 BST 2015 armv7l GNU/Linux
vcgencmd version
Aug 20 2015 17:44:52 
Copyright (c) 2012 Broadcom
version 3f87086448257aa66881de858a0b4b0e6daa8719 (clean) (release)
sudo dtc -I fs /proc/device-tree
FATAL ERROR: Couldn't opendir() "/proc/device-tree": No such file or directory

**Comment by XECDesign** [comment]
You do not appear to have device tree enabled, which prevents the necessary modules from being loaded automatically. You could modprobe rpisense-fb and rpisense-js or stick them in /etc/modules.

**Comment by Forsinogul** [comment]
I have enabled device tree in raspi-config and it works.  thanks

**Comment by XECDesign** [comment]
Glad to hear it. Have fun.

**Comment by ARKopp** [comment]
I also have the same problem. But I am using kano

**Comment by XECDesign** [comment]
I'm sorry, I only support the official foundation Raspbian distribution. I don't own or use kano and am not familiar with how they set up the software, so I won't be able to help.

**Comment by bennuttall** [comment]
I saw a tweet recently that they were thinking of adding it soon. For now you can use [Raspbian](https://www.raspberrypi.org/downloads/).

**Comment by ARKopp** [comment]
yes i just got it. Alejandro just send me Kano Jesse. Hope it works.
